CC23x0R5DriverLibrary: CMSIS Core Register Access Functions
CMSIS Core Register Access Functions
Functions and Instructions Reference
Functions
__STATIC_FORCEINLINE void __enable_irq (void)
Enable IRQ Interrupts.
__STATIC_FORCEINLINE void __disable_irq (void)
Disable IRQ Interrupts.
__STATIC_FORCEINLINE uint32_t __get_CONTROL (void)
Get Control Register.
__STATIC_FORCEINLINE void __set_CONTROL (uint32_t control)
Set Control Register.
__STATIC_FORCEINLINE uint32_t __get_IPSR (void)
Get IPSR Register.
__STATIC_FORCEINLINE uint32_t __get_APSR (void)
Get APSR Register.
__STATIC_FORCEINLINE uint32_t __get_xPSR (void)
Get xPSR Register.
__STATIC_FORCEINLINE uint32_t __get_PSP (void)
Get Process Stack Pointer.
__STATIC_FORCEINLINE void __set_PSP (uint32_t topOfProcStack)
Set Process Stack Pointer.
__STATIC_FORCEINLINE uint32_t __get_MSP (void)
Get Main Stack Pointer.
__STATIC_FORCEINLINE void __set_MSP (uint32_t topOfMainStack)
Set Main Stack Pointer.
__STATIC_FORCEINLINE uint32_t __get_PRIMASK (void)
Get Priority Mask.
__STATIC_FORCEINLINE void __set_PRIMASK (uint32_t priMask)
Set Priority Mask.
__STATIC_FORCEINLINE uint32_t __get_FPSCR (void)
Get FPSCR.
__STATIC_FORCEINLINE void __set_FPSCR (uint32_t fpscr)
Set FPSCR.
Detailed Description
Function Documentation
__enable_irq()
__STATIC_FORCEINLINE void __enable_irq (void)
Enable IRQ Interrupts.
Enables IRQ interrupts by clearing the I-bit in the CPSR. Can only be executed in Privileged modes.
References __ASM.
Referenced by IntEnableMaster().
__disable_irq()
__STATIC_FORCEINLINE void __disable_irq (void)
Disable IRQ Interrupts.
Disables IRQ interrupts by setting the I-bit in the CPSR. Can only be executed in Privileged modes.
References __ASM.
Referenced by IntDisableMaster(), and PMCTLResetSystem().
__get_CONTROL()
__STATIC_FORCEINLINE uint32_t __get_CONTROL (void)
Get Control Register.
Returns the content of the Control Register.
Returns
Control Register value
References __ASM, and __STATIC_FORCEINLINE.
__set_CONTROL()
__STATIC_FORCEINLINE void __set_CONTROL (uint32_t control)
Set Control Register.
Writes the given value to the Control Register.
Parameters
[in] control Control Register value to set
References __ASM, and __STATIC_FORCEINLINE.
__get_IPSR()
__STATIC_FORCEINLINE uint32_t __get_IPSR (void)
Get IPSR Register.
Returns the content of the IPSR Register.
Returns
IPSR Register value
References __ASM.
__get_APSR()
__STATIC_FORCEINLINE uint32_t __get_APSR (void)
Get APSR Register.
Returns the content of the APSR Register.
Returns
APSR Register value
References __ASM.
__get_xPSR()
__STATIC_FORCEINLINE uint32_t __get_xPSR (void)
Get xPSR Register.
Returns the content of the xPSR Register.
Returns
xPSR Register value
References __ASM.
__get_PSP()
__STATIC_FORCEINLINE uint32_t __get_PSP (void)
Get Process Stack Pointer.
Returns the current value of the Process Stack Pointer (PSP).
Returns
PSP Register value
References __ASM, and __STATIC_FORCEINLINE.
__set_PSP()
__STATIC_FORCEINLINE void __set_PSP (uint32_t topOfProcStack)
Set Process Stack Pointer.
Assigns the given value to the Process Stack Pointer (PSP).
Parameters
[in] topOfProcStack Process Stack Pointer value to set
References __ASM, and __STATIC_FORCEINLINE.
__get_MSP()
__STATIC_FORCEINLINE uint32_t __get_MSP (void)
Get Main Stack Pointer.
Returns the current value of the Main Stack Pointer (MSP).
Returns
MSP Register value
References __ASM, and __STATIC_FORCEINLINE.
__set_MSP()
__STATIC_FORCEINLINE void __set_MSP (uint32_t topOfMainStack)
Set Main Stack Pointer.
Assigns the given value to the Main Stack Pointer (MSP).
Parameters
[in] topOfMainStack Main Stack Pointer value to set
References __ASM, and __STATIC_FORCEINLINE.
__get_PRIMASK()
__STATIC_FORCEINLINE uint32_t __get_PRIMASK (void)
Get Priority Mask.
Returns the current state of the priority mask bit from the Priority Mask Register.
Returns
Priority Mask value
References __ASM, and __STATIC_FORCEINLINE.
Referenced by IntDisableMaster(), and IntEnableMaster().
__set_PRIMASK()
__STATIC_FORCEINLINE void __set_PRIMASK (uint32_t priMask)
Set Priority Mask.
Assigns the given value to the Priority Mask Register.
Parameters
[in] priMask Priority Mask
References __ASM, and __STATIC_FORCEINLINE.
__get_FPSCR()
__STATIC_FORCEINLINE uint32_t __get_FPSCR (void)
Get FPSCR.
Returns the current value of the Floating Point Status/Control register.
Returns
Floating Point Status/Control register value
References __ASM.
__set_FPSCR()
__STATIC_FORCEINLINE void __set_FPSCR (uint32_t fpscr)
Set FPSCR.
Assigns the given value to the Floating Point Status/Control register.
Parameters
[in] fpscr Floating Point Status/Control value to set
References __ASM.