CC23x0R5DriverLibrary: interrupt.c File Reference
interrupt.c File Reference
#include "interrupt.h"
#include "cpu.h"
#include "debug.h"
#include "../inc/hw_ints.h"
#include "../inc/hw_types.h"
#include "../cmsis/core/core_cm0plus.h"
Functions
static void IntDefaultHandler (void)
The default interrupt handler.
static __attribute__ ((section(".ramVecs"), aligned(256)))
Global pointer to the (dynamic) interrupt vector table when placed in SRAM.
void IntUnregister (uint32_t intNum)
Unregisters an interrupt handler in the dynamic vector table.
void IntSetPriority (uint32_t intNum, uint8_t priority)
Sets the priority of an interrupt.
int32_t IntGetPriority (uint32_t intNum)
Gets the priority of an interrupt.
bool IntIsEnabled (uint32_t intNum)
Check whether an interrupt is enabled.
void IntEnable (uint32_t intNum)
Enables an interrupt or system exception.
void IntDisable (uint32_t intNum)
Disables an interrupt or system exception.
void IntSetPend (uint32_t intNum)
Pends an interrupt.
bool IntGetPend (uint32_t intNum)
Checks if an interrupt is pending.
void IntClearPend (uint32_t intNum)
Unpends an interrupt.
Function Documentation
IntDefaultHandler()
static void IntDefaultHandler (void) static
The default interrupt handler.
This is the default interrupt handler for all interrupts. It simply loops forever so that the system state is preserved for observation by a debugger. Since interrupts should be disabled before unregistering the corresponding handler, this should never be called.
Returns
None
References __attribute__().
Referenced by IntUnregister().
__attribute__()
static __attribute__ ((section(".ramVecs"), aligned(256))) static
Global pointer to the (dynamic) interrupt vector table when placed in SRAM.
Interrupt vector table is placed at ".ramVecs" defined in the linker file provided by Texas Instruments.
Note
See interrupt.c for compiler specific implementation!
References ASSERT, and SCB.
Referenced by IntDefaultHandler().